name: Pioneer
on: [pull_request, push]

jobs:
  pioneer_build_ubuntu:
    name: Ubuntu Build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x]
    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: build
      run: |
        yarn install --frozen-lockfile
        yarn workspace pioneer build
    - name: lint
      run: |
        yarn workspace pioneer lint

  pioneer_build_osx:
    name: MacOS Build
    runs-on: macos-latest
    strategy:
      matrix:
        node-version: [12.x]
    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: build
      run: |
        yarn install --frozen-lockfile
        yarn workspace pioneer build
    - name: lint
      run: |
        yarn workspace pioneer lint
